on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository:  ContainerizedCI/pomoscicd
          path: pomoscicd

      - name: Build, Push and Release a Docker container to Heroku. # Your custom step name
        uses: gonuit/heroku-docker-deploy@v1.3.3 # GitHub action name (leave it as it is).
        with:

          email: ${{ secrets.HEROKU_EMAIL }}
          
 
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
   
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}

          dockerfile_directory: ./

          dockerfile_name: Dockerfile

          docker_options: "--no-cache"

          process_type: web
    