name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v2

      - name: Build Docker Image
        run: docker build -t registry.heroku.com/pomodoros/web .

      - name: Log in to Heroku Container Registry
        run: heroku container:login

      - name: Push Docker Image to Heroku Container Registry
        run: docker push registry.heroku.com/pomodoros/web

      - name: Release to Heroku
        run: heroku container:release web -a pomodoros
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
